<?php

/**
 * @file
 * Module to help test jQuery Update.
 */

/**
 * Implements hook_init().
 */
function jquery_update_test_init() {
  // Add libraries so that the script tags appear in basic pages.
  backdrop_add_library('system', 'ui.autocomplete');
  backdrop_add_library('system', 'jquery.form');
  backdrop_add_library('system', 'cookie');
}

/**
 * Implements hook_menu().
 */
function jquery_update_test_menu() {
  $items['jquery-update-test/backdrop-add-js'] = array(
    'title' => 'backdrop_add_js()',
    'page callback' => 'jquery_update_test_backdrop_add_js',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Menu callback to output return value of backdrop_add_js().
 */
function jquery_update_test_backdrop_add_js() {
  backdrop_json_output(backdrop_add_js());
}
